apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
  annotations:
    linkerd.io/inject: disabled