FROM gradle:6.7.0-jdk8 AS build
WORKDIR /home
COPY EarthquakeAdaptor/ .
RUN gradle build

FROM openjdk:8-jre-slim
RUN mkdir /app
COPY --from=build /home/build/libs/*.jar /app/dist.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/dist.jar"]